GET http://127.0.0.1:5001/compassprdms/asia-east1/addlineurl HTTP/1.1
content-type: application/json

{
  "destination": "xxxxxxxxxx",
  "events": [
    {
      "replyToken": "nHuyWiB7yP5Zw52FIkcQobQuGDXCTA",
      "type": "message",
      "mode": "active",
      "timestamp": 1462629479859,
      "source": {
        "type": "group",
        "groupId": "Ca56f94637c...",
        "userId": "U4af4980629..."
      },
      "webhookEventId": "01FZ74A0TDDPYRVKNK77XKC3ZR",
      "deliveryContext": {
        "isRedelivery": false
      },
      "message": {
        "id": "444573844083572737",
        "type": "text",
        "quoteToken": "q3Plxr4AgKd...",
        "text": "https://www.chinatimes.com/newspapers/20240820000224-260204?chdtv"
      }
    }
  ]
}
###
GET http://127.0.0.1:5001/compassprdms/us-central1/addext HTTP/1.1
content-type: application/json

{"data": {
  "title": "AMD宣布為AM5主機板釋出AGESA 1.2.0.2 BIOS韌體，解放Ryzen 9000處理器的105W cTDP模式與改善多CCD延遲",
  "date": "2024-09-30",
  "author": "Chevelle.fu",
  "content": "AMD於AMD X870E、X870主機板解禁後宣布為AMD 600系列與AMD 800系列的主機板釋出AGESA Pi 1.2.0.2 BIOS韌體，進一步提升Ryzen 9000系列處理器的性能，其中針對Ryzen 5 9600X、Ryzen 7 9700X提供獲得AMD官方嚴謹測試且不影響保固的105W cTDP模式，多核效能將顯著提升，同時Ryzen 7000與Ryzen 9000系列由兩個CCD構成的Ryzen 9處理器則能改善核心延遲。\n\n消費者在安裝透過板卡廠釋出包含AGESA Pi 1.2.0.2的韌體後將能進一步解放Ryzen 9000處理器的性能；其中原本設定於65W TDP的Ryzen 5 9600X、Ryzen 7 9700X可於BIOS開啟105W cTDP模式(預設為關閉，需手動於BIOS開啟)，此模式已經過AMD嚴謹測試，不會影響處理器保固，旨在顯著提升多核心運算的性能，對於單核心性能也會有些許的提升，不過AMD強調雖然工程團隊確保105W cTDP模式不會超出處理器的負荷範圍，但建議消費者須搭配合適的散熱器使用。\n\nAMD X870可支援DDR5-8000 EXPO記憶體\n\nAMD目前AM5平台主機板的功能與規格比較\n\n隨著Ryzen 9000系列一起公布的全新晶片組AMD X870與AMD X870E主機板也於即日起推出，AMD X870與AMD X870E晶片為AMD X670與AMD X670E的增強版，皆於NVMe與PCIe通道提供全速的PCIe Gen 5，同時標配USB 4介面，並支援DDR-8000 EXPO，相較DDR-6000可縮減1ns至2ns的延遲，滿足極緻玩家與超頻玩家的需求。",
  "source": "Cool3c",
  "category": "其他業界重要訊息",
  "url": "https://www.cool3c.com/article/225793",
  "id": "38859b4e-cb66-462f-95bb-48fb0a180b24"
}}
###
GET http://127.0.0.1:5001/compassprdms/asia-east1/addexthtml HTTP/1.1
content-type: application/json

{
  "url": "https://www.cool3c.com/article/222688"
}
